@startuml

object Instructor {
  firstName = "Nima"
  lastName = "Davarpanah"
  officeNumber = "3-2636"
}

object Textbook {
  title = "Clean Code: A Handbook of Agile Software Craftsmanship"
  author = "Robert Cecil Martin"
  publisher = "Pearson"
}

object Course {
  name = "CS5800 - Advanced Software Engineering"
}

Course --> Instructor : instructor
Course --> Textbook : textbook

@enduml